### ISSUE TITLE
ccn2: output dimension after first convolution

### ISSUE THREAD

**Issue by s-bl** [soumith/imagenet-multiGPU.torch#10]
Hey,

in
https://github.com/soumith/imagenet-multiGPU.torch/blob/master/models/alexnet_ccn2.lua
why is the output dimension after the first convolution 55 and not 
`54 = floor(224 - 11 + 2 * 0 / 4) + 1`?
Is it a result of an implicit padding of 2?

Thanks for your help and great work.

**Comment by soumith** [comment]
because ccn2 uses ceil, not floor
