### ISSUE TITLE
Getting not supported error for DataParallelTable type

### ISSUE THREAD

**Issue by srp1970** [soumith/imagenet-multiGPU.torch#19]
When I try this on multiple GPUs, I get this error:

th main.lua -netType overfeat -data /lscratch/prakash/Torch-Imagenet/ -backend cunn -nGPU 2

it gives error:

usr6/prakash/DNN/Torch/luajit-rocks/bin/luajit: ...ch/luajit-rocks/share/lua/5.1/cunn/DataParallelTable.lua:414: type() not supported for DataParallelTable.
stack traceback:
        [C]: in function 'error'
        ...ch/luajit-rocks/share/lua/5.1/cunn/DataParallelTable.lua:414: in function 'type'
        ...rakash/DNN/Torch/luajit-rocks/share/lua/5.1/nn/utils.lua:45: in function 'recursiveType'
        ...rakash/DNN/Torch/luajit-rocks/share/lua/5.1/nn/utils.lua:41: in function 'recursiveType'
        ...akash/DNN/Torch/luajit-rocks/share/lua/5.1/nn/Module.lua:123: in function 'cuda'
        ...ch/demos-master/imagenet-multiGPU.torch-master/model.lua:44: in main chunk

Am I missing something?

PS: It runs correctly with nGPU 1, though.

Prakash

**Comment by soumith** [comment]
thanks for the report, fixed in trunk via commit: https://github.com/soumith/imagenet-multiGPU.torch/commit/d82ecc8815f3e69692932d2dd29a4cd8fa985962

**Comment by srp1970** [comment]
Great - works for me. I get a speedup of about 1.6-1.7 with two GPUs. Need to test with 4 and more.
