### ISSUE TITLE
CPU version

### ISSUE THREAD

**Issue by srp1970** [soumith/imagenet-multiGPU.torch#20]
Do we have CPU backend for this imagenet for Torch?

**Comment by soumith** [comment]
@srp1970 we do not, but it's easy to modify to have one. However, considering that CPU will be 10x slower (or more) it is not really a practically useful backend.

**Comment by srp1970** [comment]
I agree Soumith, but I am trying to assess GPU vs CPU performance. In fact I did modify the lua scripts to get the CPU version. It was simple enough, though I am not expert in lua. Thanks anyway.

**Comment by ghost** [comment]
@srp1970 can you share how you modified the scripts to get the CPU version? Thank you
