### ISSUE TITLE
some bug in vggbn_cudnn.lua

### ISSUE THREAD

**Issue by buttomnutstoast** [soumith/imagenet-multiGPU.torch#35]
in line 43 and line 46 

```
features:add(nn.BatchNormalization(4096, 1e-3))
features:add(nn.BatchNormalization(4096, 1e-3))
```

I think it should be classifier rather than features, because the whole fully connected layer lies in GPU1 (or the preferred one)

**Comment by soumith** [comment]
You're right. Fixed via: https://github.com/soumith/imagenet-multiGPU.torch/commit/cf7d7d40be58968f34900c2f7362b979ab340bd2
