### ISSUE TITLE
When do we need to use cutorch.synchronize 

### ISSUE THREAD

**Issue by eriche2016** [soumith/imagenet-multiGPU.torch#36]
@soumith , I noticed that there are many place to use cutorch.synchronize function in the file train.lua, I want to know is it necessary to use cutorch.synchronize in these place, because in DataParallelTable  module, there is already cutorch,synchronize to consider synchronize stuff ex, the updateOutput method.   can you give me some tips about this ?  much appreciate it..

**Comment by soumith** [comment]
those synchronize calls are in places so that I can report accurate time measurements, and not for any technical purpose. In general you dont need to synchronize explicitly anywhere in cutorch.
