### ISSUE TITLE
png file in ILSVRC12

### ISSUE THREAD

**Issue by ppwwyyxx** [soumith/imagenet-multiGPU.torch#43]
The `n02105855_2933.JPEG` in ILSVRC12_img_train.tar is actually a PNG file. This is also reported here: https://github.com/cytsai/ilsvrc-cmyk-image-list

This will crash the image loader because `image.load` uses extension to get file format.

Did you manually convert it to jpg? Maybe add this to README to help others avoid this.

**Comment by soumith** [comment]
yes i manually converted it to jpg. I'll add a robust loading function.

**Comment by soumith** [comment]
hi! if you reinstall the image package, we handle this properly now.

luarocks install image
