### ISSUE TITLE
opts.backend not supported, breaks model.lua

### ISSUE THREAD

**Issue by anuragranj** [soumith/imagenet-multiGPU.torch#56]
In `opts.lua` :

```
cmd:option('-backend',     'cudnn', 'Options: cudnn | ccn2 | cunn')
```

selecting any other option apart from cudnn breaks at, model.lua :

```
if opt.backend == 'cudnn' then
    require 'cudnn'
    cudnn.convert(model, cudnn)
 elseif opt.backend ~= 'nn' then
    error'Unsupported backend'
```

Since the above script only supports 'cudnn'. We should consider either updating `opts.lua` or `model.lua`.

**Comment by szagoruyko** [comment]
it supports `nn` and `cudnn`, but yes you're right we should change `opts.lua`

**Comment by soumith** [comment]
fixed help in master
