### ISSUE TITLE
Torch.save on dataset class error with gm package

### ISSUE THREAD

**Issue by vrkrishn** [soumith/imagenet-multiGPU.torch#64]
I was trying to save the dataset class (as described in dataset.lua) but kept running into the following error:

> /home/vrkrishn/torch/install/share/lua/5.1/torch/File.lua:107: Unwritable object <userdata>
> stack traceback:
>   [C]: in function 'error'
>   /home/vrkrishn/torch/install/share/lua/5.1/torch/File.lua:107: in function 'writeObject'

As shown in the error message, there was an error in Lua's writeObject function. When I printed out the key that caused the error, I found that it originated from the parseExif function (specifically the fromBlob function) that is part of gm:Image(). I deduced that the dataset module could not properly save the defaultSampleHook field.

Therefore, I removed defaultSampleHook from the dataset.lua and the save process worked.

I am using Lua 5.1 and the latest version of Torch/gm.

**Comment by soumith** [comment]
@vrkrishn there's no longer graphicsmagick (gm) or defaultSampleHook in the current version :) , thanks for reporting though, i expect you are using a slightly older version of this repository.
