### ISSUE TITLE
Alexnet code for fbcunn

### ISSUE THREAD

**Issue by antoajayraj** [soumith/imagenet-multiGPU.torch#71]
I had been using cudnn and cunn as backend for the alexnet code (https://github.com/soumith/imagenet-multiGPU.torch). Recently I was looking at moving to fbcunn and wanted to run the same alexnet code. 

I dont see any backend available as 'fbcunn' to use. What modifications do I have to make to get the alexnet code working with fbcunn ?

**Comment by soumith** [comment]
Don't use fbcunn, it's obsolete now, i removed the fbcunn parts

**Comment by antoajayraj** [comment]
Thanks for your quick response @soumith 
Would there any performance benefit that one could get by using fblualib/fbcunn with Alexnet ? I believe I should do some code changes in the Alexnet to get the fbclualib/fbcunn benefits ?? Right ?

**Comment by soumith** [comment]
No

**Comment by antoajayraj** [comment]
Is the 'No' for performance benefits or for code changes ??

**Comment by soumith** [comment]
no for perfomance benefits. i think fbcunn Convolution code is no longer perf-relevant as it has been integrated into cudnn.
