### ISSUE TITLE
Too much time per epoch

### ISSUE THREAD

**Issue by Viresh-R** [soumith/imagenet-multiGPU.torch#75]
Hey Soumith,
I am training Alexnet on a single GPU(with NN backend). A single epoch takes around 7 hours. Is this much time per epoch normal ? Also, would switching to CUDNN backend make too much of a difference wrt time per epoch ?

**Comment by williford** [comment]
The `nn` backend does not use the GPU. You need to either use the `cunn` or `cudnn` backend/library to use the GPU.

**Comment by andyhahaha** [comment]
Hi Soumith,
I have the same problem. I am training Alexnet on 4 GPU. It takes 18 hours per epoch. What is the normal training time per epoch?  My training time is much longger than  JakeRyan1. Does that caused by the communication between GPUs?

**Comment by Viresh-R** [comment]
Hi Andy, you can reduce the time per epoch by increasing the number of data loading threads(nDonkeys).

**Comment by soumith** [comment]
@JakeRyan1 cudnn backend will be much much faster.
@andyhahaha what is the GPU used?

**Comment by andyhahaha** [comment]
@soumith  I use  eight Tesla M40

**Comment by soumith** [comment]
@andyhahaha if you use 8 GPUs of anything, you need to install the GPUs in a PCI-e topology that makes sure that all 8 GPUs map to the same CPU. It's likely that you didn't do this, and hence the huge communication slowdown is likely a bottleneck. (this is not torch-specific, but you'll likely see this on any framework).
There's two things you can do to improve your situation.
1. Install NCCL https://github.com/NVIDIA/nccl and nccl.torch https://github.com/ngimel/nccl.torch
2. Just use 4-GPUs at a time.
