### ISSUE TITLE
Code does not resize images to 256x256

### ISSUE THREAD

**Issue by sozubek** [soumith/imagenet-multiGPU.torch#76]
Hi,
I want to train AlexNet on ImageNet dataset. I preprocessed the original images with the following command given in the Readme file.

find . -name "*.JPEG" | xargs -I {} convert {} -resize "256^>" {}

Then I got images that have one of their sides sized 256. After this I was thinking that the images are resized to 256x 256 and then cropped to 224x224 as written in the AlexNet paper. But the resizing to 256x256 does not take place in the loadImage() function in donkey.lua . The input image has the same size as the output that comes out of image.scale() function. So training is done on 224x224 images that are croppped from 256xN sized images where N>= 256.

Is this a bug or is it intended to be this way? 
I added the loadImage function to the end of the message for reference.

Best,
Serdar

opt.imageSize = 256
opt.cropSize = 224

local loadSize   = {3, opt.imageSize, opt.imageSize}
local sampleSize = {3, opt.cropSize, opt.cropSize} 

local function loadImage(path)
   local input = image.load(path, 3, 'float')
   -- find the smaller dimension, and resize it to loadSize (while keeping aspect ratio)
   if input:size(3) < input:size(2) then
      input = image.scale(input, loadSize[2], loadSize[3] \* input:size(2) / input:size(3))
   else
      input = image.scale(input, loadSize[2] \* input:size(3) / input:size(2), loadSize[3])
   end
   return input
end

**Comment by soumith** [comment]
it is intended to be this way.
