### ISSUE TITLE
syncParameters() bug without consequences

### ISSUE THREAD

**Issue by tomsercu** [soumith/imagenet-multiGPU.torch#79]
Commit edcbd57 train.lua disabled the `:syncParameters()` call for any model where a DPT is wrapped inside (all owt-style models): needsSync will be nil even though the wrapped DPT has it set to true.
I could submit a PR with a fix like this:

```
for _, dpt in ipairs(model:findModules('nn.DataParallelTable')) do
   if dpt.needsSync then dpt:syncParameters() end
end
```

At the other hand, since on `:forward()` call the DPT will automatically call `:syncParameters()`,  I think this bug didn't have any consequences (but didn't test to make sure).
Any reason to not just remove the three lines, and let `:forward()` take care of it? @szagoruyko

**Comment by soumith** [comment]
if you could send a PR to fix it, that'll be great. DPT doesn't need syncParameters anymore so it can be removed completely.
