### ISSUE TITLE
SqueezeNet issue

### ISSUE THREAD

**Issue by rracinskij** [soumith/imagenet-multiGPU.torch#92]
Hi,
I get a following error while trying this code:
```
local model = squeezenet(2)
print(model:forward(torch.rand(3,224,224))
```

> THNN.lua:109: Wrong number of input channels! Input has 64 channels, expected 128 at /tmp/luarocks_nn-scm-1-4428/nn/lib/THNN/generic/SpatialConvolutionMM.c:92

**Comment by dimkastan** [comment]
Try the following: model:forward(torch.rand(1,3,224,224))
In this call, 1 corresponds to a batch of size 1.

**Comment by rracinskij** [comment]
Hi, thank you! Didn't think of adding a batch dimension.
